version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  mongodbUser:
    image: mongo
    container_name: mongodbUser
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - ./user:/data/db
  mongodbBooks:
    image: mongo
    command: mongod --port 27018
    container_name: mongodbBooks
    ports:
      - 27018:27018
    restart: unless-stopped
    volumes:
      - ./books:/data/db
  user-microservice:
    container_name: user-microservice
    image: user
    build: ./user-microservice
    ports:
      - 1323:1323
    depends_on:
      - broker
      - zookeeper
      - mongodbUser
    restart: unless-stopped

  books-microservice:
    container_name: books-microservice
    image: books
    build: ./books-microservice
    ports:
      - 1322:1322
    depends_on:
      - user-microservice
      - broker
      - zookeeper
      - mongodbBooks
    restart: unless-stopped
  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - user-microservice
      - books-microservice
    restart: unless-stopped
